import { mainnet, sepolia, polygon, polygonAmoy } from "viem/chains"

// StakeToLearnCourse contract ABI
export const STAKE_TO_LEARN_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "admin", type: "address" },
      { indexed: true, internalType: "bytes32", name: "enrollmentId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "AdminClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "courseId", type: "string" },
      { indexed: false, internalType: "uint256", name: "stakeAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "requiredCompletion", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "requiredTestAverage", type: "uint256" },
    ],
    name: "CourseConfigured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "student", type: "address" },
      { indexed: true, internalType: "string", name: "courseId", type: "string" },
      { indexed: true, internalType: "bytes32", name: "enrollmentId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "stakedAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "enrollmentTime", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "courseEndTime", type: "uint256" },
    ],
    name: "Enrolled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "enrollmentId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "completionPercentage", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "testAverage", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalLearningMinutes", type: "uint256" },
    ],
    name: "ProgressUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "student", type: "address" },
      { indexed: true, internalType: "bytes32", name: "enrollmentId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "string", name: "reason", type: "string" },
    ],
    name: "RefundClaimed",
    type: "event",
  },
  {
    inputs: [{ internalType: "bytes32", name: "enrollmentId", type: "bytes32" }],
    name: "adminClaimExpiredStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "enrollmentId", type: "bytes32" }],
    name: "canAdminClaim",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "enrollmentId", type: "bytes32" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "courseId", type: "string" },
      { internalType: "uint256", name: "stakeAmount", type: "uint256" },
      { internalType: "uint256", name: "durationDays", type: "uint256" },
      { internalType: "uint256", name: "requiredCompletion", type: "uint256" },
      { internalType: "uint256", name: "requiredTestAverage", type: "uint256" },
      { internalType: "uint256", name: "dailyLearningMinutes", type: "uint256" },
    ],
    name: "configureCourse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "courses",
    outputs: [
      { internalType: "uint256", name: "stakeAmount", type: "uint256" },
      { internalType: "uint256", name: "duration", type: "uint256" },
      { internalType: "uint256", name: "requiredCompletion", type: "uint256" },
      { internalType: "uint256", name: "requiredTestAverage", type: "uint256" },
      { internalType: "uint256", name: "dailyLearningMinutes", type: "uint256" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "courseId", type: "string" }],
    name: "enrollInCourse",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "enrollments",
    outputs: [
      { internalType: "address", name: "student", type: "address" },
      { internalType: "string", name: "courseId", type: "string" },
      { internalType: "uint256", name: "stakedAmount", type: "uint256" },
      { internalType: "uint256", name: "enrollmentTime", type: "uint256" },
      { internalType: "uint256", name: "courseEndTime", type: "uint256" },
      { internalType: "bool", name: "completed", type: "bool" },
      { internalType: "bool", name: "refunded", type: "bool" },
      { internalType: "bool", name: "adminClaimed", type: "bool" },
      { internalType: "uint256", name: "completionPercentage", type: "uint256" },
      { internalType: "uint256", name: "testAverage", type: "uint256" },
      { internalType: "uint256", name: "totalLearningMinutes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "courseId", type: "string" }],
    name: "getCourseConfig",
    outputs: [
      { internalType: "uint256", name: "stakeAmount", type: "uint256" },
      { internalType: "uint256", name: "duration", type: "uint256" },
      { internalType: "uint256", name: "requiredCompletion", type: "uint256" },
      { internalType: "uint256", name: "requiredTestAverage", type: "uint256" },
      { internalType: "uint256", name: "dailyLearningMinutes", type: "uint256" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "enrollmentId", type: "bytes32" }],
    name: "getEnrollment",
    outputs: [
      { internalType: "address", name: "student", type: "address" },
      { internalType: "string", name: "courseId", type: "string" },
      { internalType: "uint256", name: "stakedAmount", type: "uint256" },
      { internalType: "uint256", name: "enrollmentTime", type: "uint256" },
      { internalType: "uint256", name: "courseEndTime", type: "uint256" },
      { internalType: "bool", name: "completed", type: "bool" },
      { internalType: "bool", name: "refunded", type: "bool" },
      { internalType: "bool", name: "adminClaimed", type: "bool" },
      { internalType: "uint256", name: "completionPercentage", type: "uint256" },
      { internalType: "uint256", name: "testAverage", type: "uint256" },
      { internalType: "uint256", name: "totalLearningMinutes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStats",
    outputs: [
      { internalType: "uint256", name: "_totalEnrollments", type: "uint256" },
      { internalType: "uint256", name: "_totalStaked", type: "uint256" },
      { internalType: "uint256", name: "_totalRefunded", type: "uint256" },
      { internalType: "uint256", name: "_totalClaimed", type: "uint256" },
      { internalType: "uint256", name: "_currentBalance", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "student", type: "address" }],
    name: "getStudentEnrollments",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "enrollmentId", type: "bytes32" }],
    name: "isEligibleForRefund",
    outputs: [
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "string", name: "", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GRACE_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }, { internalType: "uint256", name: "", type: "uint256" }],
    name: "studentEnrollments",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalClaimed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalEnrollments",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRefunded",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalStaked",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "enrollmentId", type: "bytes32" },
      { internalType: "uint256", name: "completionPercentage", type: "uint256" },
      { internalType: "uint256", name: "testAverage", type: "uint256" },
      { internalType: "uint256", name: "totalLearningMinutes", type: "uint256" },
    ],
    name: "updateProgress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const

// Contract addresses for stake-to-learn
export const STAKE_CONTRACT_ADDRESSES = {
  [mainnet.id]: process.env.NEXT_PUBLIC_STAKE_CONTRACT_ADDRESS_MAINNET,
  [sepolia.id]: process.env.NEXT_PUBLIC_STAKE_CONTRACT_ADDRESS_SEPOLIA,
  [polygon.id]: process.env.NEXT_PUBLIC_STAKE_CONTRACT_ADDRESS_POLYGON,
  [polygonAmoy.id]: process.env.NEXT_PUBLIC_STAKE_CONTRACT_ADDRESS_AMOY,
} as const
